USE [master]
GO
/****** Object:  Database [ParkingLot]    Script Date: 07/09/2022 03:11:18 ******/
CREATE DATABASE [ParkingLot]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ParkingLot', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ParkingLot.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ParkingLot_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ParkingLot_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ParkingLot] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ParkingLot].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ParkingLot] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ParkingLot] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ParkingLot] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ParkingLot] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ParkingLot] SET ARITHABORT OFF 
GO
ALTER DATABASE [ParkingLot] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ParkingLot] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ParkingLot] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ParkingLot] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ParkingLot] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ParkingLot] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ParkingLot] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ParkingLot] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ParkingLot] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ParkingLot] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ParkingLot] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ParkingLot] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ParkingLot] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ParkingLot] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ParkingLot] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ParkingLot] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ParkingLot] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ParkingLot] SET RECOVERY FULL 
GO
ALTER DATABASE [ParkingLot] SET  MULTI_USER 
GO
ALTER DATABASE [ParkingLot] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ParkingLot] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ParkingLot] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ParkingLot] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ParkingLot] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ParkingLot', N'ON'
GO
ALTER DATABASE [ParkingLot] SET QUERY_STORE = OFF
GO
USE [ParkingLot]
GO
/****** Object:  Table [dbo].[EntrancesAndExitsVehicles]    Script Date: 07/09/2022 03:11:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EntrancesAndExitsVehicles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NumberLicense] [nchar](10) NOT NULL,
	[IsEnterOrExit] [bit] NOT NULL,
	[Timestamp] [datetime] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NotAllowedEnterVehicles]    Script Date: 07/09/2022 03:11:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NotAllowedEnterVehicles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NumberLicense] [nchar](10) NULL,
	[Image] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](150) NOT NULL,
	[Timestamp] [datetime] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [index1]    Script Date: 07/09/2022 03:11:18 ******/
CREATE UNIQUE NONCLUSTERED INDEX [index1] ON [dbo].[EntrancesAndExitsVehicles]
(
	[NumberLicense] ASC,
	[Timestamp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [index1]    Script Date: 07/09/2022 03:11:18 ******/
CREATE UNIQUE NONCLUSTERED INDEX [index1] ON [dbo].[NotAllowedEnterVehicles]
(
	[NumberLicense] ASC,
	[Timestamp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EntrancesAndExitsVehicles] ADD  DEFAULT (getdate()) FOR [Timestamp]
GO
ALTER TABLE [dbo].[NotAllowedEnterVehicles] ADD  DEFAULT (getdate()) FOR [Timestamp]
GO
USE [master]
GO
ALTER DATABASE [ParkingLot] SET  READ_WRITE 
GO
